// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../../../../encoding/json/jsontext/models.js";

/**
 * Invoke is the sole application binding. Commands retain their existing
 * names and arguments; callers cannot select executables or native windows.
 */
export function Invoke(command: string, args: json$0.RawMessage): $CancellablePromise<any> {
    return $Call.ByName("github.com/MylesMCook/burf/app/native/desktop.Service.Invoke", command, args);
}
