// The live demo's stand-in for lucide-react/dynamic (aliased in
// vite.config.ts for --mode demo only). The real one splits every lucide
// icon into its own chunk, some 1,700 files; the demo knows the icons its
// built-in plugins name, and draws a puzzle piece for any other.
import type { LucideProps } from "lucide-react";
import {
  ActivityIcon,
  AppWindowIcon,
  ArrowDownWideNarrowIcon,
  ArrowUpRightIcon,
  BellIcon,
  BookMarkedIcon,
  BotIcon,
  ChartColumnIcon,
  CheckIcon,
  ChevronsDownUpIcon,
  ChevronsUpDownIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleDotIcon,
  CircleIcon,
  CircleMinusIcon,
  CircleSlashIcon,
  CircleXIcon,
  CloudOffIcon,
  CopyIcon,
  DotIcon,
  EllipsisIcon,
  ExternalLinkIcon,
  FolderGit2Icon,
  GitBranchIcon,
  GitBranchPlusIcon,
  GitCompareArrowsIcon,
  GitMergeIcon,
  GitPullRequestClosedIcon,
  GitPullRequestCreateIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  GlobeIcon,
  HandIcon,
  HistoryIcon,
  InfoIcon,
  KeyRoundIcon,
  LayersIcon,
  LoaderCircleIcon,
  MessageSquareIcon,
  NotebookPenIcon,
  PanelRightIcon,
  PencilIcon,
  PlayIcon,
  PlugIcon,
  PlusIcon,
  PuzzleIcon,
  RadioIcon,
  RefreshCwIcon,
  SearchIcon,
  SendIcon,
  ServerIcon,
  SparklesIcon,
  SquareIcon,
  SquareTerminalIcon,
  SquareXIcon,
  TerminalIcon,
  TerminalSquareIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UnplugIcon,
  UploadIcon,
  UserRoundIcon,
  UsersIcon,
  WorkflowIcon,
  WrenchIcon,
} from "lucide-react";

const icons = {
  "activity": ActivityIcon,
  "app-window": AppWindowIcon,
  "arrow-down-wide-narrow": ArrowDownWideNarrowIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "bell": BellIcon,
  "book-marked": BookMarkedIcon,
  "bot": BotIcon,
  "chart-column": ChartColumnIcon,
  "check": CheckIcon,
  "chevrons-down-up": ChevronsDownUpIcon,
  "chevrons-up-down": ChevronsUpDownIcon,
  "circle-alert": CircleAlertIcon,
  "circle-check": CircleCheckIcon,
  "circle-dot": CircleDotIcon,
  "circle-minus": CircleMinusIcon,
  "circle-slash": CircleSlashIcon,
  "circle-x": CircleXIcon,
  "circle": CircleIcon,
  "cloud-off": CloudOffIcon,
  "copy": CopyIcon,
  "dot": DotIcon,
  "ellipsis": EllipsisIcon,
  "external-link": ExternalLinkIcon,
  "folder-git-2": FolderGit2Icon,
  "git-branch-plus": GitBranchPlusIcon,
  "git-branch": GitBranchIcon,
  "git-compare-arrows": GitCompareArrowsIcon,
  "git-merge": GitMergeIcon,
  "git-pull-request-closed": GitPullRequestClosedIcon,
  "git-pull-request-create": GitPullRequestCreateIcon,
  "git-pull-request-draft": GitPullRequestDraftIcon,
  "git-pull-request": GitPullRequestIcon,
  "globe": GlobeIcon,
  "hand": HandIcon,
  "info": InfoIcon,
  "key-round": KeyRoundIcon,
  "layers": LayersIcon,
  "loader-circle": LoaderCircleIcon,
  "message-square": MessageSquareIcon,
  "notebook-pen": NotebookPenIcon,
  "panel-right": PanelRightIcon,
  "pencil": PencilIcon,
  "play": PlayIcon,
  "plug": PlugIcon,
  "plus": PlusIcon,
  "puzzle": PuzzleIcon,
  "radio": RadioIcon,
  "refresh-cw": RefreshCwIcon,
  "history": HistoryIcon,
  "search": SearchIcon,
  "send": SendIcon,
  "server": ServerIcon,
  "sparkles": SparklesIcon,
  "square-terminal": SquareTerminalIcon,
  "terminal-square": TerminalSquareIcon,
  "square-x": SquareXIcon,
  "square": SquareIcon,
  "terminal": TerminalIcon,
  "trash-2": Trash2Icon,
  "triangle-alert": TriangleAlertIcon,
  "unplug": UnplugIcon,
  "upload": UploadIcon,
  "user-round": UserRoundIcon,
  "users": UsersIcon,
  "workflow": WorkflowIcon,
  "wrench": WrenchIcon,
};

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons) as IconName[];

export function DynamicIcon({ name, ...props }: LucideProps & { name: IconName }) {
  const Icon = icons[name] ?? PuzzleIcon;
  return <Icon {...props} />;
}
